serokell/time-warp-nt

examples/Discovery.hs
src/Mockable/Channel.hs
src/Mockable/Exception.hs
src/Network/Discovery/Abstract.hs
src/Network/Discovery/Transport/InMemory.hs
src/Network/Discovery/Transport/Kademlia.hs
src/Node.hs
src/Node/Internal.hs

Quick fix to dispatcher so that the state map doesn't grow without
bound. It's a naive solution: clean up all finished threads and then
receive. It's probably not ideal for throughput.
NetworkDiscovery:
Find an InMemory instantiation (which requires a patch to
network-transport-inmemory that's up as a pull request currently) as
well as one backed by Kademlia. There's also an example where you can
spin up locally as many nodes as you want. They'll use a TCP transport
and Kademlia to discover each-other's end point addresses and then send
pings at random intervals.

Fix leak, prototype of a NetworkDiscovery abstraction

---

examples/Discovery.hs
examples/PingPong.hs
src/Node/Internal.hs

This is the one true way. See the discussion here:
https://github.com/haskell-distributed/network-transport-tcp/pull/44
network-transport only guarantees that
`concat sentChunks == concat receivedChunks`
which neatly handles the case of `[]` as `concat [] = ""`.
Types which serialize to `""` are now acceptable.

Concatenate chunks before attempting to parse

---

bench/Network/Common/Bench/Network/Commons.hs
bench/Network/Receiver/Main.hs
bench/Network/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
node-sketch.cabal
src/Mockable/Concurrent.hs
src/Mockable/Monad.hs
src/Mockable/Production.hs
src/Node.hs
src/Node/Internal.hs
test/Test/Util.hs

- `Async` mocking has been added. @georgeee has requested adding `mapConcurrently`. That can certainly be done and will be useful.
- `startNode` has been removed in favour of a function called `node` which doesn't spawn workers for you, but gives you a `Node m` and `SendActions m` to work with, shutting down the `Node m` automatically when your work is done.
- The dependency on `time-warp` has been removed. Surely we don't want this to depend on `time-warp`, since it's a rework of that package.
- I have some concerns about `repeatForever` and `sleepForever`. They can both be implemented in a simpler way in terms of other primitives, and I don't think `sleepForever` is a good idea at all. Let's discuss.

Add Async mocking; change node start/stop; some questions about time/delay mocking

---

test/Test/Util.hs

99000 instead of 100000 as a temp solution.

[] Tests passed, a little bit lower heavy parcel's size.

---

node-sketch.cabal
src/Data/NonEmptySet.hs
src/Node.hs
src/Node/Internal.hs
test/Test/NodeSpec.hs
test/Test/Util.hs

In this program:
```Haskell
node transport prng listeners $ \theNode -> do
<some program>
putStrLn "Closing"
putStrLn "Closed"
```
`"Closed"` will not be printed until every one of the node's running listeners has finished, and no new conversation handlers will be spun up *by the dispatcher* after "Closing" is printed (at which point the network-transport `EndPoint` created by `node` is closed, so we can't complete the SYN/ACK handshake).
NB: it s possible for the programmer to try to make new connections after the `EndPoint` has closed, for instance if threads are left running with `theNode` in scope after the monadic term given as the final argument of `node` finishes. When this is done, an exception is thrown.
I noticed that the conversation style test would sometimes fail. It happened …

Dispatcher waits for handlers to finish

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
examples/abuse/Main.hs
node-sketch.cabal
src/Data/NonEmptySet.hs
src/Mockable/Exception.hs
src/Mockable/Instances.hs
src/Mockable/Metrics.hs
src/Mockable/Production.hs
src/Mockable/SharedAtomic.hs
src/Mockable/SharedExclusive.hs
src/Network/Transport/Abstract.hs
src/Network/Transport/Concrete.hs
src/Network/Transport/Concrete/TCP.hs
src/Network/Transport/ConnectionBuffers.hs
src/Node.hs
src/Node/Internal.hs
src/Node/Message.hs
src/Node/Util/Monitor.hs
stack.yaml
test/Test/Util.hs

This is a requirement that was discussed with @georgeee 
We need to have application-specific, network-agnostic data about a peer, but it was determined that sending this information for every message would be too heavy. Another option was to have each node carry an application-specific identifier, and other nodes keep state associating those identifiers with this peer data, and I suppose having a way to demand peer data in case it's not known for that identifier.
The solution implemented here complicates the node quite a bit but it should be good. The first lightweight connection to a peer shall always be responsible for sending the peer data. Once the data is sent (`send` returns) other connections to that peer can begin sending data. The dispatcher therefore shall always know the peer …

Node carries static peer data and transmits on new connections

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
examples/abuse/Main.hs
node-sketch.cabal
src/Mockable/Instances.hs
src/Mockable/Metrics.hs
src/Mockable/Production.hs
src/Mockable/SharedAtomic.hs
src/Mockable/SharedExclusive.hs
src/Network/Transport/Abstract.hs
src/Network/Transport/Concrete.hs
src/Network/Transport/Concrete/TCP.hs
src/Network/Transport/ConnectionBuffers.hs
src/Node.hs
src/Node/Internal.hs
src/Node/Message.hs
stack.yaml

The current implementation of our node has a single dispatcher thread, pulling network-transport `Event`s from an unbounded `Chan` and then determining what to do with them, typically putting received data into some other unbounded `Chan`. That's no good. network-transport-tcp will pull data from sockets as fast as it can, no matter what.
Even with queueing and buffering for network-transport-tcp as in https://github.com/haskell-distributed/network-transport-tcp/pull/46 we're still not quite there. We could define some `QDisc` which bounds the input buffers for each socket, but we're still left with only one means of output: `receive :: EndPoint -> Event`. It aggregates events from *every* socket, and then our dispatcher still hands out the data to the unbounded `Chan`s of the handlers. …

Backpressure

---

src/Mockable/Concurrent.hs
src/Mockable/Exception.hs
src/Mockable/Monad.hs
src/Mockable/Production.hs
src/Mockable/SharedExclusive.hs
src/Node.hs
src/Node/Internal.hs
stack.yaml

Just as we must plug the input channels of outbound handlers when the endpoint closes or a connection is lost, we must also fill the peer data MVar, or else the handlers may block indefinitely.
These cases were revealed by cardano-node. In that program, it's quite common for a handler to try to do its thing even though the node has gone down normally (time slave before real node).

Fill peer data exclusive on errors; improve logging

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
examples/abuse/Main.hs
examples/abuse/README.md
src/Network/Transport/Abstract.hs
src/Network/Transport/Concrete/TCP.hs
src/Node.hs
test/Test/Util.hs

See the [README](https://github.com/serokell/time-warp-nt/blob/ac0cf3c3c64b56b92ac3609fb0fa6d9215d3ee01/examples/abuse/README.md)
Also included in this PR are fixes for some mistakes which were uncovered while writing up documentation.
- The type of `Node.node` changes: the `NodeActions` (which includes the listeners) must be computed purely (rather than in `m`) and can use the components of the `Node` itself only lazily. That's because the listeners must be defined *prior* to the end point being brought up. Prior to this change there was a gap in time between bringing the end point up, and defining the listeners, so it was possible (though highly unlikely) that the system would try to run a listener which is not yet defined.
- The definition of `Node.ConversationActions` changes so that …

Improved abuse and backpressure demonstration

---

node-sketch.cabal
src/Node/Internal.hs
stack.yaml
test/Test.hs
test/Test/NodeSpec.hs
test/Test/Util.hs

The race was incredibly rare, probably never to be seen except on self-connections: it was possible to get the ACK before the handler/nonce was registered in the state.
Testing is improved: two sloppy new cases for self connections and peer data. Also updated the spec to use in-memory and TCP transports.

Improve testing, fix race on bidirectional connections

---

stack.yaml

So we don't have a mismatch between compiler and resolver anymore, which
made it difficult to install ghci and intero.
Also, dropped `extra-deps` that are in LTS 8.2, and updated `serokell-util`.

Update to LTS Haskell 8.2

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
stack.yaml
test/Test/Util.hs

A network-transport-tcp change for a separate bind address has
landed in master. The type of createTransport has changed: the third
argument takes the actual bound port and returns a host address and port
to use as the external address.

Update stack.yaml for nt-(tcp)(inmemory)

---

src/Network/QDisc/Fair.hs
src/Network/QDisc/Simulation.hs
test/Test/NodeSpec.hs

We may want to use this in conjunction with some mutable blacklist
determined by metrics gathered by a node, so as to induce artificial
delays on certain peers deemed to be abusive.
@kantp This might be useful in your abuse tests, if we can come
up with a suitable delay for a peer based upon the node's metrics
(for instance, using this feature https://github.com/serokell/time-warp-nt/pull/27).

Fair QDisc can de-prioritize certain peers

---

src/Mockable/Production.hs
src/Mockable/SharedAtomic.hs
src/Node/Internal.hs

"live bytes" means those bytes which have been delivered to a handler
which is currently running. This supports a conservative assumption that
a handler uses memory proportional to the amount of bytes given to its
input channel.
The dispatcher thread is of course responsible for reporting the
increments, but `spawnHandler` does most of the work. Other programs can
inspect the node statistics, held in a `SharedAtomic`. The idea is that
a `QDisc` or perhaps the dispatcher thread itself will use this
information to induce an artificial delay on one or all peers in case of
heavy load (lots of live bytes).

Track total live bytes for each peer

---

examples/Discovery.hs
examples/PingPong.hs
node-sketch.cabal
src/Mockable/Production.hs
src/Network/QDisc/Fair.hs
src/Network/Transport/Concrete/TCP.hs
src/Node.hs
src/Node/Internal.hs
src/Node/Message.hs
src/Node/Util/Monitor.hs

This reduces the noise at compile time, making it easier to spot warnings that might be important.
Also, replaced some incomplete pattern matches with Exceptions.

[Tw 127] remove compiler warnings

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
src/Mockable/Concurrent.hs
src/Mockable/Production.hs
src/Node.hs
src/Node/Internal.hs
test/Test/NodeSpec.hs
test/Test/Util.hs

A programmable timeout in microseconds is given when a node is created. If a bidirectional connection does not hear an ACK before this time then it's killed with a `Timeout` exception. A test case is included.

[TW-114] timeout waiting for ACK

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
src/Node.hs
src/Node/Internal.hs
test/Test/NodeSpec.hs
test/Test/Util.hs

Instead, they just need a way to create and to close an EndPoint. For
the low-level startNode, the whole Node is in scope. For the high level
node, only the mutable cell of the node's state is in scope.
This allows us to use non-standard features of a transport, for instance
the TCP transport's QDisc, to create an EndPoint to be used by the node.
There is a patch for network-transport-tcp which allows the choice of a
particular QDisc for each new EndPoint, but it can only be done through
the TCP internals as the network-transport newEndPoint type doesn't
permit such a thing. With the changes here, it's possible to use the TCP
internals to create a special QDisc with the node's state in scope,
thereby using traffic metrics to control queueing.
Relevant network-transport-tcp change is …

node/startNode don't take a Transport

---

src/Node/Internal.hs

This caused many warnings to appear in self-connection tests. A self
connection makes a local and a remote entry (it's both, technically) but
adding the remote handler wouldn't bump the count in the map, so it was
removed prematurely.

Fix typo in pstAddHandler

---

src/Mockable/Concurrent.hs
src/Mockable/Production.hs
src/Node/Internal.hs

A fairly egregious oversight by me! The application needs to know if the
dispatcher stops doing its thing.

Correct dispatcher exception throwing / handling

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
src/Network/Discovery/Transport/Kademlia.hs
src/Network/Transport/Abstract.hs
src/Node.hs
src/Node/Internal.hs
stack.yaml
test/Test/Util.hs

In one application it was necessary to change the monad over which a transport operates. `hoistTransport` implements this.

Use nt-tcp NAT, hoist functions for abstract transport

---

bench/Sender/Main.hs
test/Test/Util.hs

network-transport-tcp revision bump caused benchmark sender to fail because of an export change.

Fix benchmark sender import, tests, for nt-tcp interface change

---

src/Node/Internal.hs

We'll probably want to serialize `NodeId`s without manually coercing to/from `EndPointAddress`.

NodeId is Generic, Binary

---

src/Node/Internal.hs

This will help in our logs to identify nodes.

Log our timewarp NodeId when we sart up a node

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
src/Node.hs
src/Node/Internal.hs
test/Test/NodeSpec.hs
test/Test/Util.hs

Previously, sending a single message would not show the peer data. Now it does, because a single message interaction is just a conversation where one of the send or receive types is `Void`. The conversation does not proceed until the peer data of the remote peer is available, as it always will be because they must ACK the request, and peer data is always available if there's at least one incoming connection. (There is a longstanding but rare bug caused by `EventConnectionLost` which I'll fix soon).
Also included: the set of listeners is computed from the peer data each time a conversation is begun. In a typical application where the peer data specifies version information, this could be very useful: the set of listeners can depend upon the version info, rather than having a fixed set of …

[TW-138] provide peer data on all interactions

---

node-sketch.cabal
src/NTP/Client.hs

This is part of planned efforts to temporally get rid of
`Mockable Throw` & `Mockable Catch` usages.
Also `MonadMask` is removed, since `bracketOnError` can be performed
in terms of `MonadBaseControl IO`.

[CSL-738] Use most typical monad constraints in NTP

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
node-sketch.cabal
src/Node.hs
src/Node/Internal.hs
src/Node/Message/Binary.hs
src/Node/Message/Class.hs
src/Node/Message/Decoder.hs
src/Node/Message/Store.hs
stack.yaml
test/Test/NodeSpec.hs
test/Test/Util.hs

- Outgoing messages are split into chunks of at most some number of
bytes. This value must be properly configured when running over
network-transport-tcp, to be smaller than the maximum receive size.
- Node.Message has been split up and the Packable/Unpackable classes
rolled into one class Serializable, which demands an incremental
decoder which mimics the on from Data.Binary.Get
- In a conversation, 'recv' takes a limit on the number of bytes which
will be read.
- Can use store instead of binary for deserialization, as shown in the
implementation of Node.Message.Store
TODO: give a CBOR-backed implementation and use criterion to get some real
performance numbers.

[TW-149] Redesign of message serialization

---

src/Node/Message/Binary.hs
src/Node/Message/Store.hs

Instead of appending on the accumulator at each step (quadratic),
accumulate a list and concatenate the whole thing before
decoding (linear).

[TW-149] improve store decoder complexity

---

examples/Discovery.hs
src/Network/Discovery/Transport/Kademlia.hs
stack.yaml

The branch used by cardano-sl uses a special Kademlia revision that takes an external host address in addition to the bind address.
I'm fairly confident this Kademlia change isn't needed. The external address is only ever given to peers who already know this node's external address, so why bother?
But anyway, the revision is used by cardano-sl, so if we want to build that against time-warp master then we have to update time-warp to use it. We're going to port all mentions of Kademlia out of cardano-sl and here to time-warp and this is the first step.

Bump Kademlia version

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
node-sketch.cabal
src/Network/Broadcast/Relay/Class.hs
src/Network/Broadcast/Relay/Logic.hs
src/Network/Broadcast/Relay/Types.hs
src/Network/Broadcast/Relay/Util.hs
src/Node.hs
src/Node/Internal.hs
test/Test/NodeSpec.hs
test/Test/Util.hs

Inv/Req/Data relaying mechanism spliced from cardano-sl and stripped down to what (I'm fairly sure) is minimally sufficient for relay broadcast.
```Haskell
-- 'relayer' relays a message, in this particular case by putting it into a queue
-- which is cleared by 'relayWorker', in the same way that the current cardano-sl
-- implementation does it (concurrent send to all neighbours).
-- However this one is parameterized by the way in which the targets are
-- determined.
(relayer, relayWorker) <- simpleRelayer (determineNextTarget :: Maybe NodeId -> m (Set NodeId))
-- Relay listeners need to know how to relay (a field in the 'Relay' datatype).
let listeners = relayListeners
[ relayGroup1 relayer :: Relay packingType m
, relayGroup2 relayer :: Relay packingType m
]
-- An example 'NodeAction': …
```

[TW-148] import relay stuff from CSL

---

src/Mockable/Production.hs

This fixes `MonadBaseControl` instance that was causing CSL-1209 bug. See more in YT description. TLDR it was delaying some execution when combined with `control`.

[CSL-1209] Fix MonadBaseControl instance for Production

---

src/JsonLog/CanJsonLog.hs
src/JsonLog/JsonLogT.hs
src/Network/Broadcast/Relay/Class.hs
src/Network/Broadcast/Relay/Types.hs
stack.yaml

In https://github.com/input-output-hk/cardano-sl/pull/967/ I removed as many transformer layers as possible, `JsonLogT` being one of them. Instead, I need to put this `JsonLogConfig` into a `ReaderT` at the bottom of the transformer stack, and then use `jsonLogDefault` to implement the `CanJsonLog` instance.
This patch does not change the semantics of the module and merely exports `JsonLogConfig` and `jsonLogDefault`.
(Ah, and I also fixed Haddock build)

[CSL-1154] JsonLogConfig type

---

src/Node/Message/Store.hs

This PR exports 'storeDecoder' to avoid boilerplate code and copy-paste from `time-warp` to `cardano-sl`.

Export 'storeDecoder'

---

src/Network/Broadcast/OutboundQueue.hs
src/Network/Broadcast/OutboundQueue/Classification.hs
src/Network/Broadcast/OutboundQueue/Demo.hs

This set of nodes is still subject to the enqueueing policy. This PR also adds a new kind of message type called `MsgRequestData`. This new message type, along with the `enqueueTo` set of API calls, can be used when requesting data (such as blocks) from peers that are known to have them. The advantage is that the queue can then make an educated guess of _which_ of the peers-known-to-have-the-data we should request the data from; for example, we prefer to ask data from relay nodes over asking data from core nodes so that we don't put more load on the system when there are nodes in recovery mode.
This required some internal restructuring, primarily because we now have more than one kind of enqueueing instruction that can be returned by the enqueueing policy; the old `Enqueue` instruction is …

Add ability to enqueue to a specific set of nodes

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
src/Node.hs
src/Node/Internal.hs
src/Node/Message/Binary.hs
src/Node/Message/Class.hs
src/Node/Message/Decoder.hs
src/Node/Message/Store.hs
test/Test/NodeSpec.hs
test/Test/Util.hs

- The `Decoder` type is parameterzsed by some `* -> *` type.
- A packing type need not (shouldn't) be inhabited, but must be an instance of the new `PackingType` class which determines concrete monadic context for encoding and decoding. For existing store and binary packing types these are all `Identity`.
- To use a packing type instance `packingType` to run a node over `m`, a `Packing packingType m` must be given. See `unpack` and `pack` in `Node.Message.Class`.
- Fix `recvNext` in case end of input happens during a partial parse. Previously it would `End` but now it correctly throws `NoParse`.
- `continueDecoding` now takes a single `ByteString` rather than `[ByteString]`.

Redesign of packing type to support CBOR decoding

---

bench/Receiver/Main.hs
bench/Sender/Main.hs
examples/Discovery.hs
examples/PingPong.hs
src/Bench/Network/Commons.hs
src/Node.hs
src/Node/Message/Class.hs
test/Test/Util.hs

This is the simplest way to satisfy CSL-849, but I'm tempted to do more.
The message code / name should not be determined by the send type of the
conversation. Really what we want to express is a code for a listener.

[CSL-849] messageCode :: Word16 to identify conv

---

src/Network/Broadcast/OutboundQueue.hs
src/Network/Broadcast/OutboundQueue/Demo.hs
src/Network/Broadcast/OutboundQueue/Types.hs

This is a crucial PR, because in the policy as it had been implemented requests for block headers and requests for blocks were given the lowest priority. This would cause relay nodes that are inundated with transactions (which were given a higher priority) to never request blocks, therefore getting behind, finally entering recovery mode, and then being unable to exit recovery mode because transactions were also given higher priority than the "request headers" messages.
The original spec did not talk about these kinds of messages, but the newer specs do and indeed give them high priority. This PR brings the code in line with this spec, but there are still some open questions:
* I have increased the `MaxInFlight` values for core-to-relay, relay-to-core, and edge-to-relay communication to a …

Bring policies in line with latest spec / bugfixes

---

src/Network/Broadcast/OutboundQueue.hs
src/Network/Broadcast/OutboundQueue/Demo.hs
src/Network/Broadcast/OutboundQueue/Types.hs

They've been moved to cardano-sl. ~~Will reference the pull request once it's been made.~~
https://github.com/input-output-hk/cardano-sl/pull/1347
Also included a commit to extend the `Peers` datatype with a classification of those peers which do not necessarily appear in the routing lists. This is useful because sometimes we route to peers even though they don't appear in our routing list, as in `MsgGetBlocks`.

[CSL-1505] Do not define default policies; peer classification for non-routed peers

---

src/Network/Broadcast/OutboundQueue.hs
src/Network/Broadcast/OutboundQueue/Demo.hs
src/Network/Broadcast/OutboundQueue/Types.hs

Previously, a message which had been dequeued and completed would still
occupy space in the queue. How long it remains effectively in the queue
depends upon the rate limit. In cardano-sl a rate limit of 1 per second
is used, and so it was observed that a message would always stay in the
queue for at least one second. This caused recovery mode to fail. The
MsgRequestHeaders would hang around for ~0.8 seconds after the
conversation had finished, during which time two MsgRequestBlocks are
enqueued, but the second would fail because there's 2 message ahead of
it. Failing to get the needed blocks, the node would try again,
enqueuing a MsgRequestHeaders and repeating the cycle of failure.
The problem arises in recovery mode. There's a block retrieval queue and one
thread (the retrieval worker) …

[CSL-1515] decrement in flight before delay

---

src/Network/Broadcast/OutboundQueue.hs

Introduced by me in #93.
It resulted in puzzling messages like "rejected this alternative because
it has 0 ahead, which is more than the maximum 0". Reason: didn't
include the in-flight count in the message.

Fix mistake in queue debug message

---

.travis.yml
src/Network/Broadcast/OutboundQueue.hs
src/Network/Broadcast/OutboundQueue/Types.hs

Peers which are not routed in the queue's peers term now appear in the
'unknown' set and are appropriately classified and routed.

[CSL-1549] correct enqueue subset

---

examples/PingPong.hs
node-sketch.cabal
src/Node/Util/Monitor.hs

This PR restores `Node.Util.Monitor`, but only `setupMonitor`.
This allows us to still drop `ekg`.
cc @dcoutts

Restore setupMonitor

---

bench/LogReader/Main.hs
src/JsonLog/JsonLogT.hs
src/NTP/Example.hs
stack.yaml
test/Test/Util.hs

I need newer universum in cardano-sl. It requires to also bump log-warper and there was a breaking change there, so I need to bump it here.
I also updated LTS to be the same as the one in cardano-sl.

Use newer universum, log-warper, LTS

---

src/Network/Broadcast/OutboundQueue.hs

The comparison was the wrong way around.

Fix exceedsBucketSize

---

node-sketch.cabal
src/Network/Broadcast/OutboundQueue/Types.hs
test/Test/Network/Broadcast/OutboundQueueSpec.hs

This maybe-over-complicated PR improves `removePeer` to skip empty lists.
See here for the full rational and debugging: https://issues.serokell.io/issue/CSL-1652#comment=96-7493
I have also added a bunch of properties to demonstrate this was indeed an issue prior to this patch:
But that now everything is green:

[CSL-1652] Improve removePeer

---

src/Network/Broadcast/OutboundQueue.hs

This simple PR drops the queue name (i.e. `qSelf`) from the EKG metrics.
@domenkozar This is how the dashboard will look like when we update Cardano accordingly:
Good enough?

[CSL-1702] Drop queue name from EKG metrics

---

src/Node/Internal.hs

This tiny PR stems from a conversation with @avieth and from [CSL-1709](https://issues.serokell.io/issue/CSL-1709). In order to troubleshoot and debug some subtle issues, it's nice to get as many logging as we can of the underlying error causes.
In particular, this PR logs the reason why a connection was lost. Hopefully it will be enough to track down the place inside `network-transport-tcp` where this is coming from (and why), to understand better what's going on.
Feel free to add more useful logging as part of this PR.

[CSL-1709] Log the reason why the connection was lost.

---

bench/LogReader/Main.hs
src/Bench/Network/Commons.hs
src/NTP/Example.hs
stack.yaml

This bump up is required to bump up `log-warper` in `cardano-sl`.

[CSL-1739] Bump up log-warper to 1.3.0

---

src/Data/NonEmptySet.hs

The first commit alters the implementation of NonEmptySet so that `Node.Internal.nodeDispatcher` doesn't leak space anymore. The second one fixes a bug in the implementation of `insert` where you could end up with two equal elements in the set.

Fix space leak and bug in the implementation of insert in NonEmptySet

---

src/Node/Internal.hs
stack.yaml

Previously it was required that the programmer correctly bracket
connectToPeer against disconnectFromPeer. But that was a losing battle:
it was impossible to do it right, because connectToPeer was too big to
use as the acquire part of a bracket against disconnectFromPeer: it was
possible that the shared state would be updated with a stable
established connection, but the whole action still exit with an exception
(at sendPeerDataIfNecessary). That would cause disconnectFromPeer not to
run, leaving an inconsistent state. Consequently, the peers would be
unable to communicate, as they would not agree on whether the peer data
needs to be transmitted.

[CSL-1645] connectToPeer bracketing
