- examples/Discovery.hs
- examples/PingPong.hs
- src/Mockable/Channel.hs
- src/Node.hs
- src/Node/Internal.hs
The ping/pong example is now really ping/pong.
> Bidirectional connections (conversations) working

- README.md
- examples/PingPong.hs
It's not about some task, it's just about little improvements.
> [] Little additions in README and PingPong example.

- src/Node/Internal.hs
I mistakenly believed that a `ConnectionClosed` or `EventConnectionLost` would come for every `ConnectionOpened` eventually, but that's not true. If the end point is closed while connections are opened,  then we need to plug their input channels with `Nothing`, otherwise their handlers may hang indefinitely while trying to receive data. This was observed in the conversation-style tests.
Also included is a cherry-picked commit to wait for the handlers to finish.
I observe many warning about connection lost while running the tests. I will investigate and fix that.
> Plug input channels on EndPointClosed

- src/Mockable/Channel.hs
- src/Mockable/Class.hs
- src/Mockable/Concurrent.hs
- src/Mockable/CurrentTime.hs
- src/Mockable/Exception.hs
- src/Mockable/Metrics.hs
- src/Mockable/Production.hs
- src/Mockable/SharedAtomic.hs
- src/Mockable/SharedExclusive.hs
Also added -O2 GHC options to relevant modules.
@kantp
> SPECIALIZE INLINE Production mockables

- src/NTP/Client.hs
- src/NTP/Util.hs
* More failure-stable
* Fixed: [CSL-965] NTP shouldn't fail if any of servers fails
> Ntp clean up

- src/Network/Transport/Abstract.hs
> Cherry-pick commit 221d55: hoistTransport and friends

- src/Network/Discovery/Transport/Kademlia.hs
- stack.yaml
This is required for `cardano-sl:cardano-sl-0.4` to `cardano-sl:master` merge
> Merge `avieth/nat` to `time-warp-nt-0.1.1`

- examples/Discovery.hs
- src/Network/Discovery/Transport/Kademlia.hs
- stack.yaml
An old branch that ought to be merged.
> [CSL-1075] Kademlia configurable bind host

- stack.yaml
cc @Martoon-00 @ChShersh 
this makes `stack --nix build` happen.
> Fix compilation on nix

- bench/Receiver/Main.hs
- bench/Sender/Main.hs
- examples/Discovery.hs
- examples/PingPong.hs
- examples/abuse/Main.hs
- src/Node.hs
- src/Node/Internal.hs
- src/Node/Util/Monitor.hs
- test/Test/NodeSpec.hs
- test/Test/Util.hs
This will be useful in application which wish to extend the EKG server with their own metrics.
> [DEVOPS-74] Setup monitoring without starting server

- .gitignore
- .travis.yml
- node-sketch.cabal
- src/JsonLog.hs
- src/JsonLog/CanJsonLog.hs
- src/JsonLog/Event.hs
- src/JsonLog/JsonLogT.hs
- stack.yaml
Moved JSON logging from cardano-sl to time-warp-nt.
> [TW-150] added JSON logging

- bench/Receiver/Main.hs
- bench/Sender/Main.hs
- examples/Discovery.hs
- examples/PingPong.hs
- node-sketch.cabal
- src/Mockable/Concurrent.hs
- src/Mockable/Exception.hs
- src/Mockable/Production.hs
- src/Network/Broadcast/OutboundQueue.hs
- src/Network/Broadcast/OutboundQueue/Classification.hs
- src/Network/Broadcast/OutboundQueue/ConcurrentMultiQueue.hs
- src/Network/Broadcast/OutboundQueue/Demo.hs
- src/Node.hs
- src/Node/Conversation.hs
- src/Node/OutboundQueue.hs
- test/Test/NodeSpec.hs
- test/Test/Util.hs
Includes Edsko's work on a complex outbound queueing mechanism. It's been modified so that it can fulfill the abstract `OutboundQueue` interface.
https://github.com/input-output-hk/cardano-sl/pull/1116
> [TW-148] outbound queueing

- node-sketch.cabal
- src/NTP/Client.hs
> [CSL-738] Simplify constraints in NTP

- src/Node/Internal.hs
This prevents a simple attack (described in the ticket) in which anybody
who knows what peer data you expect can fill up your heap with bytes.
Note that there's another side to the story in case this is backed by
network-transport-tcp: the transport's QDisc. If the simple unbounded
QDisc is used, the attack will probably still work, because the
unbounded Chan will fill up with data faster than the dispatcher can
remove it. Using a one-place or fair QDisc mitigates this.
> [TW-144] ignore incoming data if handler finished

- src/Network/Broadcast/OutboundQueue.hs
- src/Network/Broadcast/OutboundQueue/Demo.hs
The set of buckets is static and ordered, which simplifies reasoning about the 'Peers' values we're working with, as well as integration in the settlement layer.
> Generalize to multiple buckets

- QUEUE_METRICS.md
- src/Network/Broadcast/OutboundQueue.hs
- src/Network/Broadcast/OutboundQueue/Demo.hs
https://issues.serokell.io/issue/CSL-1462
https://issues.serokell.io/issue/CSLREQ-198
https://issues.serokell.io/issue/CSL-1465
> EKG counters

- src/Network/Broadcast/OutboundQueue.hs
Trivial commit needed for proper implementation of max subscribers.
> Show and Eq instances for MaxBucketSize

- src/Network/Broadcast/OutboundQueue.hs
- src/Network/Broadcast/OutboundQueue/Types.hs
Also added a few missing Show instances that I missed earlier.
> Introduce clearFailureOf

- src/Network/Broadcast/OutboundQueue/Demo.hs
- src/Network/Broadcast/OutboundQueue/Types.hs
https://issues.serokell.io/issue/TW-161
Targeting `avieth/csl1515`
> [TW-161] MsgRequestBlockHeaders argument

- src/Network/Broadcast/OutboundQueue.hs
This simple PR adds a new function called `bucketSpareCapacity` to be used to query an `OutboundQueue` regarding the "free slots" it has to accept more peers. It can be used by application code to implement services to check if we hit our subscription limit for a particular <queue, bucket> combination.
cc @edsko @dcoutts @avieth
> add the "bucketSpareCapacity" function

- QUEUE_METRICS.md
In response to https://issues.serokell.io/issue/CSL-1651 .
> Improvements to the queue metrics docs
